In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [5]:
# 1. Input
# 1.1 Image preprocessing
img = cv2.imread("vertical.png", cv2.IMREAD_GRAYSCALE)
img = img / 255
img_flattened = img.flatten()

img2 = cv2.imread("horizontal.png", cv2.IMREAD_GRAYSCALE)
img2 = img2 / 255
img2_flattened = img.flatten()

In [6]:
dataset = np.array([img_flattened,
                    img2_flattened])

labels = np.array([0, 1])

print("Dataset")
print(dataset)

Dataset
[[0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]]


In [7]:
# 2. Weights
weights = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

for i in range(1):
    print("Round: ", i + 1)

    temporary_weights = weights.copy()
    for image, label in zip(dataset, labels):
        convolution = sum(image * weights)
        print("Image")
        print(image)

        # 3. Activation function
        result = sigmoid(convolution)

        # 5. Error
        error = result - label
        print("Label", label)
        print("Error", error)

        # 6. Adjustment
        adjustment = error * sigmoid_der(result)
        print("Adjustment", adjustment)

        temporary_weights -= np.dot(image, adjustment)

    weights = temporary_weights.copy()
    print("Weights", weights)
    print()

# # 4. Output
# # Vertical 0
# if result < 0.5:
#     print("Vertical")
# # Horizontal 1
# elif result > 0.5:
#     print("Horizontal")

Round:  1
Image
[0. 1. 0. 0. 1. 0. 0. 1. 0.]
Label 0
Error 0.8175744761936437
Adjustment 0.17371175481161166
Image
[0. 1. 0. 0. 1. 0. 0. 1. 0.]
Label 1
Error -0.18242552380635635
Adjustment -0.03876033167077969
Weights [0.5        0.36504858 0.5        0.5        0.36504858 0.5
 0.5        0.36504858 0.5       ]

