In [8]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [9]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

#derivada da função sigmoid
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [15]:
def feed_forward(input, weights):
    convolution = np.dot(input, weights)
    result = sigmoid(convolution)
    return result


def back_propagation(result, label, input):
    error = result - label
    adjustment = error * sigmoid_der(result)
    #input.T - matriz transposta
    weights_update = np.dot(input.T, adjustment)
    return weights_update

In [16]:
# 1. Input
# 1.1 Image preprocessing
img = cv2.imread("vertical.png", cv2.IMREAD_GRAYSCALE)
img = img / 255
img_flattened = img.flatten()

img2 = cv2.imread("horizontal.png", cv2.IMREAD_GRAYSCALE)
img2 = img2 / 255
img2_flattened = img2.flatten()

dataset = np.array([img_flattened,
                    img2_flattened])

labels = np.array([0, 1])

print("Dataset")
print(dataset)

# 2. Weights
weights = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

for i in range(1):
    print("Round: ", i + 1)

    result = feed_forward(dataset, weights)
    weights -= back_propagation(result, labels, dataset)


print("Weights", weights)
print()

# Input
# [[0. 1. 0. 0. 1. 0. 0. 1. 0.]
#  [0. 0. 0. 1. 1. 1. 0. 0. 0.]]

# [0.8175744761936437 0.8175744761936437]

Dataset
[[0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]]
Round:  1
Weights [0.5        0.32628825 0.5        0.53876033 0.36504858 0.53876033
 0.5        0.32628825 0.5       ]

